### ISSUE TITLE
How to recup caseId

### ISSUE THREAD

**Issue by DRAKUN** [Bonitasoft-Community/getting-started-tutorial#1]
Bonjour
ceci n'est vraiment un bug mais j'aimerais savoir 
Dans le BDM vous avez créer un champ caseId - Long - Mandatory
j'ai cherché partout , meme dans le connecteur create requests , mais je ne trouve pas comment vous avez initialisé cette valeur.
j'ai essayé de faire la meme chose sur mon model mais il me dit a chaque caseId cannot be null ce qui est tout a fait normal car le champ est obligatoire.

Merci pour cet exemple qui m'a permis de mettre en place une belle application.

**Comment by pozil** [comment]
Bonjour,

Désolé mais il n'y a pas de champ `caseId` dans cet exemple-ci (processus "Simple Travel Request" du tutoriel "Getting started").
Vous devez probablement faire référence à un autre exemple?

Ceci dit, l'utilisation de l'identifiant du cas est un classique donc voici comment le récupérer.

En général, on le récupère dès l'instanciation du processus en passant par la valeur initiale (Default value) de l'instance du BDM.
Vous disposez justement d'une variable `processInstanceId` qui est est pré-définie et pré-assignée par le système. Il vous suffit donc de la copier dans votre BDM.
Pour se faire, il suffit simplement d'ajouter cette ligne de code dans le script groovy qui initialise votre BDM :
`myBdm.caseId = processInstanceId`

J'espère que cela répond à votre question.

**Comment by DRAKUN** [comment]
bonjour, cela répond parfaitement à ma question, j'ignorais simplement que le processInstanceId est égale au caseId.
merci pour tout. Bonita est merveilleux

 `demandeFVar.isApproved = false`
`demandeFVar.isEngage = false`
`demandeFVar.caseId = processInstanceId`
