### ISSUE TITLE
When I click on URL returns 404 Page not found

### ISSUE THREAD

**Issue by LasanthaPrasad** [Bonitasoft-Community/getting-started-tutorial#4]
Hi, 
I have successfully followed your steps, It is working with default Forms in Portal. 
but when I click on URL on Application Page " http://localhost:48882/bonita/apps/travel/" it returns 404 Page not found. 

Please advice me. 
BR
Lasantha Prasad

**Comment by amottier** [comment]
Can you maybe share a screenshot of your application configuration in Bonita Portal administration view?

**Comment by LasanthaPrasad** [comment]
Hi, I am using Bonitasoft v7.5.2.. it didnt correctly import  "page-TravelTool.zip"  and dont display as import to resource page.

**Comment by amottier** [comment]
I just did a test and manage to successfully add the "page-TravelTool.zip" as a new ressource in my Portal. Can you give more details about what error message you get? Also maybe share the log files.

**Comment by LasanthaPrasad** [comment]
Hi Thanks for your reply. 
Finally I figured out the issue. My PC is having 32bit and 64bit java. Environment variable was set for 32bit JAVA. I changed Environment Variable to 64bit and installed Bonitasoft v7.5.4. now everything is okay. 
Thanks
