### ISSUE TITLE
When I click on Submit button nothing happens 

### ISSUE THREAD

**Issue by apekshajit** [Bonitasoft-Community/getting-started-tutorial#5]
Ideally request should get raised... I am unable to raise the travel request.
I have followed all the steps...
My observation is  In UI designer there should be some value at "Target URL on success" 
or  
formOutput  value provided by bundle is -  return { 'travelRequestInput': $data.formInput.travelRequestInput };

Please help me with this. On click of submit process should initiate the request. I have rechecked entire application setting twice.

**Comment by amottier** [comment]
Can you please export and share the .bos file with your workspace content?

Note that for debugging I recommend to take a look at the Bonita Engine log file (available from Studio "Help" menu) and also open the web browser developer tools in the network tab to see the detail about the HTTP request response when you click on the submit button.

Thanks.

**Comment by apekshajit** [comment]
Hello,
Thank you for sharing this information. I have checked the same and finally it worked. Could please share the sample steps for designing one process. Actually I want to create one sample process and run in Bonitasoft. I have checked the getting started manual provided in documentation but some how it didn’t work properly.
Kindly share sample steps to design a process in Bonitasoft 6+.

Thank you,
Apex

**Comment by amottier** [comment]
If you have troubles creating a new process when following the [getting started tutorial](https://documentation.bonitasoft.com/bonita/7.6/getting-started-tutorial), please post a description of your issue on [Bonita community forum](https://community.bonitasoft.com/questions-and-answers). When posting your question please post a link to download your .bos file and the Engine log file.
